# Generated by Django 2.2 on 2022-12-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商家编号')),
                ('business_name', models.CharField(max_length=10, verbose_name='商家用户名')),
                ('business_password', models.CharField(max_length=10, verbose_name='商家密码')),
                ('business_phone', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='商家电话')),
                ('storename', models.CharField(max_length=10, verbose_name='店名')),
                ('minamount', models.IntegerField(verbose_name='起送')),
                ('delivery', models.IntegerField(verbose_name='配送费')),
                ('business_status', models.IntegerField(choices=[(1, '营业中'), (0, '休息中')], verbose_name='营业状态')),
            ],
            options={
                'verbose_name': '商家信息',
                'verbose_name_plural': '商家信息',
                'db_table': 'business',
                'ordering': ['business_id'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False, verbose_name='菜品编号')),
                ('meal_name', models.CharField(max_length=10, verbose_name='菜品名称')),
                ('meal_description', models.TextField(verbose_name='菜品描述')),
                ('meal_left', models.IntegerField(verbose_name='菜品库存')),
                ('meal_graph', models.TextField(verbose_name='菜品图片')),
                ('meal_price', models.IntegerField(verbose_name='菜品价格')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='商家')),
            ],
            options={
                'verbose_name': '菜品信息',
                'verbose_name_plural': '菜品信息',
                'db_table': 'meal',
                'ordering': ['meal_id'],
            },
        ),
        migrations.CreateModel(
            name='Orderinfo',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('canteen_name', models.CharField(max_length=5, verbose_name='食堂')),
                ('new_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='备注名')),
                ('total_price', models.FloatField(verbose_name='总价')),
                ('address', models.TextField(verbose_name='地址')),
                ('arrive_time', models.DateTimeField(verbose_name='预定送达时间')),
                ('order_status', models.IntegerField(choices=[(0, '已下单'), (1, '已接单'), (2, '已送达')], verbose_name='订单状态')),
                ('order_time', models.DateTimeField(verbose_name='下单时间')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='商家')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'orderinfo',
                'ordering': ['-order_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_number', models.IntegerField(verbose_name='菜品数量')),
                ('meal', models.ForeignKey(on_delete=None, to='business.Meal', verbose_name='菜品')),
                ('order', models.ForeignKey(on_delete=None, to='business.Orderinfo', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单中菜品信息',
                'verbose_name_plural': '订单中菜品信息',
                'db_table': 'order_meal',
                'ordering': ['order_id', 'meal_id'],
            },
        ),
    ]
