# Generated by Django 2.2 on 2022-12-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('canteenadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canteenadmin.Category', verbose_name='种类'),
        ),
        migrations.AddField(
            model_name='business',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canteenadmin.Canteen', verbose_name='食堂编号'),
        ),
        migrations.AlterUniqueTogether(
            name='ordermeal',
            unique_together={('meal', 'order')},
        ),
    ]
