# Generated by Django 2.2 on 2022-12-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userinfo_sex'),
        ('business', '0002_auto_20221208_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermeal',
            options={'ordering': ['user_id', 'meal_id'], 'verbose_name': '订单中菜品信息', 'verbose_name_plural': '订单中菜品信息'},
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='business',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='canteen_name',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='order_note',
            field=models.TextField(default=123, verbose_name='备注'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermeal',
            name='user',
            field=models.ForeignKey(default=123, on_delete=None, to='user.Userinfo', verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_graph',
            field=models.ImageField(upload_to='', verbose_name='菜品图片'),
        ),
        migrations.AlterUniqueTogether(
            name='ordermeal',
            unique_together={('meal', 'user')},
        ),
        migrations.RemoveField(
            model_name='ordermeal',
            name='order',
        ),
    ]
