# Generated by Django 2.2 on 2022-12-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20221223_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='arrive_time',
            field=models.CharField(max_length=10, verbose_name='预定送达时间'),
        ),
    ]
