# Generated by Django 2.2 on 2022-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20221223_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_time',
            field=models.CharField(max_length=50, verbose_name='下单时间'),
        ),
    ]
