# Generated by Django 2.2 on 2022-12-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20221223_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermeal',
            options={'ordering': ['user_id', 'meal_id'], 'verbose_name': '用户购物车信息', 'verbose_name_plural': '用户购物车信息'},
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_number', models.IntegerField(verbose_name='菜品数量')),
                ('meal', models.ForeignKey(on_delete=None, to='business.Meal', verbose_name='菜品')),
                ('order', models.ForeignKey(on_delete=None, to='business.Orderinfo', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单中菜品信息',
                'verbose_name_plural': '订单中菜品信息',
                'db_table': 'order_list',
                'ordering': ['order_id', 'meal_id'],
                'unique_together': {('meal', 'order')},
            },
        ),
    ]
