# Generated by Django 2.2 on 2022-12-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20221223_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_graph',
            field=models.ImageField(default=123, upload_to='', verbose_name='菜品图片'),
            preserve_default=False,
        ),
    ]
