# Generated by Django 2.2 on 2022-12-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_business_business_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='order_status',
            field=models.IntegerField(choices=[(0, '已下单'), (1, '已接单'), (2, '已送达')], default=0, verbose_name='订单状态'),
            preserve_default=False,
        ),
    ]
