# Generated by Django 2.2 on 2022-12-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20221224_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order_status',
            field=models.IntegerField(choices=[(0, '已下单'), (1, '已接单')], verbose_name='订单状态'),
        ),
    ]
