# Generated by Django 2.2 on 2022-12-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('sex', models.CharField(blank=True, max_length=1, null=True, verbose_name='性别')),
                ('user_password', models.CharField(max_length=10, verbose_name='用户密码')),
                ('user_phone', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='用户电话')),
                ('user_name', models.CharField(max_length=10, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'userinfo',
                'ordering': ['user_id'],
            },
        ),
    ]
